services:
    _defaults:
        autowire: true
        autoconfigure: true

    # DataFixtures are only available in dev environment
    SocketIoBundle\DataFixtures\:
        resource: '../../DataFixtures/'
        tags: ['doctrine.fixture.orm']