services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  SocketIoBundle\Command\:
    resource: '../../Command/'
  SocketIoBundle\Controller\:
    resource: '../../Controller/'
  SocketIoBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  SocketIoBundle\Repository\:
    resource: '../../Repository/'
  SocketIoBundle\Service\:
    resource: '../../Service/'
    
  # 明确注册 AdminMenu 服务
  SocketIoBundle\Service\AdminMenu:
    tags:
      - { name: 'easy_admin_menu.provider', priority: 10 }
